/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidedRouteImport } from './routes/guided'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidedIndexRouteImport } from './routes/guided.index'
import { Route as GuidedHistoryRouteImport } from './routes/guided.history'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidedRoute = GuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidedIndexRoute = GuidedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidedRoute,
} as any)
const GuidedHistoryRoute = GuidedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => GuidedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/guided': typeof GuidedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflows': typeof WorkflowsRoute
  '/guided/history': typeof GuidedHistoryRoute
  '/guided/': typeof GuidedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflows': typeof WorkflowsRoute
  '/guided/history': typeof GuidedHistoryRoute
  '/guided': typeof GuidedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/guided': typeof GuidedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workflows': typeof WorkflowsRoute
  '/guided/history': typeof GuidedHistoryRoute
  '/guided/': typeof GuidedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/guided'
    | '/login'
    | '/register'
    | '/workflows'
    | '/guided/history'
    | '/guided/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/workflows'
    | '/guided/history'
    | '/guided'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/dashboard'
    | '/guided'
    | '/login'
    | '/register'
    | '/workflows'
    | '/guided/history'
    | '/guided/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  GuidedRoute: typeof GuidedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guided': {
      id: '/guided'
      path: '/guided'
      fullPath: '/guided'
      preLoaderRoute: typeof GuidedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guided/': {
      id: '/guided/'
      path: '/'
      fullPath: '/guided/'
      preLoaderRoute: typeof GuidedIndexRouteImport
      parentRoute: typeof GuidedRoute
    }
    '/guided/history': {
      id: '/guided/history'
      path: '/history'
      fullPath: '/guided/history'
      preLoaderRoute: typeof GuidedHistoryRouteImport
      parentRoute: typeof GuidedRoute
    }
  }
}

interface GuidedRouteChildren {
  GuidedHistoryRoute: typeof GuidedHistoryRoute
  GuidedIndexRoute: typeof GuidedIndexRoute
}

const GuidedRouteChildren: GuidedRouteChildren = {
  GuidedHistoryRoute: GuidedHistoryRoute,
  GuidedIndexRoute: GuidedIndexRoute,
}

const GuidedRouteWithChildren =
  GuidedRoute._addFileChildren(GuidedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  GuidedRoute: GuidedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
